# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqvBIjvz4yjG9mirDPpU-Q5XFcaXoxdP
"""

import io
import chess.pgn
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount('/content/drive')

input_path = "/content/drive/MyDrive/magnikaru/filtered_games.pgn"
train_output_path = "/content/drive/MyDrive/magnikaru/train_ds.csv"
test_output_path = "/content/drive/MyDrive/magnikaru/test_ds.csv"

parsed_games = []
with open(input_path, "r", encoding="latin1") as pgn_file:
    while True:
        game = chess.pgn.read_game(pgn_file)
        if game is None:
            break

        headers = dict(game.headers)

        result = headers.get("Result", "")
        if result not in ["1-0", "0-1"]:
            continue
        binary_result = 1 if result == "1-0" else 0

        exporter = chess.pgn.StringExporter(columns=None, variations=False, comments=False)
        pgn_moves = game.accept(exporter).strip().split("\n\n")[-1]

        parsed_games.append({
            "White": headers.get("White", ""),
            "Black": headers.get("Black", ""),
            "WhiteElo": headers.get("WhiteElo", ""),
            "BlackElo": headers.get("BlackElo", ""),
            "Date": headers.get("Date", ""),
            "TimeControl": headers.get("TimeControl", ""),
            "ECO": headers.get("ECO", ""),
            "Opening": headers.get("Opening", ""),
            "Result": binary_result,
            "pgn": pgn_moves
        })
df = pd.DataFrame(parsed_games)

train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

train_df.to_csv(train_output_path, index=False)
print(f"Number of games in training set: {len(train_df)}")
val_df.to_csv(test_output_path, index=False)
print(f"Number of games in validation set: {len(val_df)}")